name: CI

on: [push]

jobs:
  deploy:
    # if: github.ref=='refs/heads/master'
    runs-on: [ubuntu-18.04]
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # - name: Install npm devDependencies
      #   run: npm install

      # - name: Run build tasks
      #   run: npm run build

      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: cd ${{ secrets.PROJECT_PATH }} && git pull && npm install && npm run build

      # - name: Deploy with rsync
      #   run: rsync -rav --delete build/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.PROJECT_PATH }}/build
